# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate rgeigen
#
name: rgeigen
channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - pkg-config
  - gawk
  - graphviz
  - doxygen==1.9.1
